app01/urls.py
from django.db import router
from django.urls import path
from app01 import views

urlpatterns = [
    path('user/list/', views.user_list),
    path('admin/register/', views.admin_register),
    path('user/add/', views.user_add),
    path('user/edit/<int:uid>', views.user_edit),
    path('user/del/<int:uid>', views.user_del),
    path('login/', views.login),
    path('logout/', views.logout),
    path('images/code/', views.images_code),
    path('test/', views.test),
    path('count/num/', views.count_num),
    path('chart/bar/',views.chart_bar),
    path('update/',views.update_pi)

]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include
from app01 import urls as app01_urls, views
from learn_notes import urls as learn

urlpatterns = [
    path('',views.login),
    path('app01/', include(app01_urls)),
    path('learn_notes/', include(learn)),
    path('admin/',admin.site.urls)
]

app01/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="余额", max_digits=18, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")
    depart = models.ForeignKey(verbose_name='部门', to="Department", to_field='id', on_delete=models.CASCADE)
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.IntegerField(verbose_name="性别", choices=gender_choices)


class AdminTable(models.Model):
    name = models.CharField(verbose_name='账号', max_length=32, null=False, unique=True)
    password = models.CharField(verbose_name='密码', max_length=32)

    class Meta:
        verbose_name_plural = verbose_name = '添加用户'

    def __str__(self) -> str:
        return f'{self.name}'

app01/views.py
import json
from .models import UserInfo, AdminTable
from django.shortcuts import render, redirect, HttpResponse
from django import forms
from .utils.encrypt import md5
from .utils.code import check_code
from django.http import JsonResponse


# Create your views here.


def user_list(request):
    queryset = UserInfo.objects.all()
    return render(request, 'user_list.html', {'queryset': queryset})


##########  Moudleform  ############
class UserForm_add(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['name', 'password', 'age', 'account', 'create_time', 'depart', 'gender']


def user_add(request):
    """add部门"""
    if request.method == 'GET':
        form = UserForm_add()
        # content = {
        #     'gender_choice': UserInfo.gender_choices,
        #     'depart_list': Department.objects.all()
        # }
        return render(request, 'user_add.html', {'form': form})
    # post提交数据
    form = UserForm_add(data=request.POST)
    if form.is_valid():
        # 保存到数据库
        form.save()
        return redirect('/app01/user/list/')
    else:
        print(form.errors)


def user_edit(request, uid):
    moud_form = UserInfo.objects.filter(id=uid).first()
    if request.method == 'GET':
        form = UserForm_add(instance=moud_form)
        return render(request, 'user_edit.html', {'form': form})

    form = UserForm_add(data=request.POST, instance=moud_form)
    if form.is_valid():
        form.save()
        return redirect('/app01/user/list')

    return render(request, 'user_edit.html', {'form': form})


def user_del(request, uid):
    UserInfo.objects.filter(id=uid).delete()
    return redirect('/app01/user/list/')


class AdminForm(forms.ModelForm):
    config_pass = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput
    )

    class Meta:
        model = AdminTable
        fields = ['name', 'password', 'config_pass']
        widgets = {
            'password': forms.PasswordInput(render_value=True)  # 密码……………………
        }

    def clean_password(self):
        password = md5(self.cleaned_data.get('password'))
        return password

    def clean_config_pass(self):
        password = self.cleaned_data.get('password')
        re_password = md5(self.cleaned_data.get('config_pass'))
        if password != re_password:
            raise ValueError("密码不一致")
        return re_password


def admin_register(request):
    if request.method == 'GET':
        form = AdminForm()
        return render(request, 'register.html', {'form': form})
    form = AdminForm(data=request.POST)
    if form.is_valid():
        form.save()
        request.session.clear()
        return redirect('/app01/login/')
    else:
        return render(request, 'register.html', {'form': form})


class LoginForm(forms.Form):
    name = forms.CharField(
        label='用户名',
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput,
        required=True
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        password = md5(self.cleaned_data.get('password'))
        return password


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        code = form.cleaned_data.pop('code')
        code_new = request.session.get('code_mage', "")
        if code.upper() != code_new.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        admin_object = AdminTable.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或者密码错误")
            return render(request, 'login.html', {'form': form})
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.name}
        return redirect('/learn_notes/learn/list/')
    return redirect('/app01/login/')


def logout(request):
    request.session.clear()
    return redirect('/app01/login/')


from io import BytesIO


def images_code(request):
    """"图片验证码"""
    img, code_string = check_code()
    request.session['code_mage'] = code_string
    # 设置超时60s
    # request.session.set_expiry('code_mage',60)
    steam = BytesIO()
    img.save(steam, 'png')
    return HttpResponse(steam.getvalue())


def test(request):
    if request.method == "GET":
        return render(request, 'test.html')
    return HttpResponse("12")


def count_num(request):
    return render(request, 'count_num.html')


def chart_bar(request):
    legend = ["A", "B"]
    xAxis = ['1月', '2月', '3月']
    data_list = [{
        "name": 'A',
        "type": 'bar',
        "data": [5, 20, 36, 10, 10, 20]
    },
        {
            "name": 'B',
            "type": 'bar',
            "data": [5, 20, 36, 10, 10, 20]
        }, ]
    result = {
        "status": True,
        "data": {
            "legend": legend,
            "xAxis": xAxis,
            "series": data_list
        },
    }
    return JsonResponse(result)

#上传图片
def update_pi(request):
    # if request.method == "GET":
    #     return render(request, 'update_pi.html')

    object_name = request.FILES.get("avatar")
    path = "./pict/"+object_name.name
    with open(path, 'wb') as f:
        for chunk in object_name.chunks():
            f.write(chunk)
    return HttpResponse("file_path")

app01/templates/1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <p>确定删除吗？</p>
        <div>
            <button onclick="handleOk">确定</button>
            <button onclick="handleCancle">取消</button>
        </div>
    </div>
</body>
</html>

app01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>笔记管理系统</title>
    {#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/tinymce/6.3.2/icons/default/icons.min.js"></script>
    {% block js %}
    {% endblock %}
    <style>

    </style>
    <script>
    {#    const html1 = document.getElementById("content-div");#}
    {#console.log(html1)#}
    </script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">笔记管理系统</a>
        </div>

        <ul class="nav navbar-nav">
            <li><a href="/app01/admin/register/">账号注册</a></li>
{#            <li><a href="/app01/user/list/">用户管理</a></li>#}
            <li><a href="/learn_notes/learn/list/">个人笔记</a></li>
            <li><a href="/learn_notes/learn/list_all/">笔记广场</a></li>
            <li><a href="/app01/count/num/">数据统计</a></li>
{#            <li><a href="/app01/update/">图片上传</a></li>#}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a>{{ request.session.info.name }}</a></li>
            <li><a href="/app01/logout">注销</a></li>
        </ul>
    </div>
    </div>
</nav>
<div>
    {% block content %}{% endblock %}
</div>

</body>

</html>

app01/templates/count_num.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
                <div class="panel panel-default">
                      <div class="panel-heading">柱状图</div>
                      <div class="panel-body">
                        <div id="m2" style="width: 1200px;height: 500px">

                        </div>
                      </div>
                </div>
        </div>

{% endblock %}
{% block js %}
    <script src="https://cdn.staticfile.org/echarts/5.2.2/echarts.min.js"></script>
        <script type="text/javascript">

        $(function(){
            intbar()
        })

     function intbar() {
         // 基于准备好的dom，初始化echarts实例
         var myChart = echarts.init(document.getElementById('m2'));

         // 指定图表的配置项和数据
         var option = {
             title: {
                 text: '业绩汇总信息',
                 left: "center",
                 textAlign: "auto"
             },
             tooltip: {},
             legend: {
                 data: [],
                 bottom: 0
             },
             xAxis: {
                 data: []
             },
             yAxis: {},
             series: []
         };

            $.ajax({
                url:'/app01/chart/bar/',
                type:"get",
                dataType:"json",
                success:function (res){
                    if (res.status){
                        option.series = res.data.series
                        option.legend.data = res.data.legend
                        option.xAxis.data = res.data.xAxis
                    }
                        // 使用刚指定的配置项和数据显示图表。
                        myChart.setOption(option);
                }
            })

     }
    </script>
{% endblock %}

app01/templates/depart_add.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
  <div class="form-group">
    <label>名称</label>
      <input type="text" class="form-control" name="title" placeholder="请输入名称">
      <button type="submit" class="btn btn-default">添加</button>
  </div>
</form>

</div>
{% endblock %}

app01/templates/depart_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
  <div class="form-group">
    <label>名称</label>
      <input type="text" class="form-control" name="title" value="{{ aa.title }}">
      <button type="submit" class="btn btn-default">提交</button>
  </div>
</form>

</div>
{% endblock %}

app01/templates/depart_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class="container">
    <div><a class="btn btn-success" href="/app01/depat/add/"> 新建部门</a></div>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">信息展示</div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>ID</th>
            <th>名称</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for queryson in queryset %}
          <tr>
            <th scope="row">1</th>
            <td>{{ queryson.id }} </td>
            <td>{{ queryson.title }}</td>
            <td>
                <a class="btn btn-primary" href="/app01/depat/edit/{{ queryson.id }}">编辑</a>
                <a class="btn btn-danger" href="/app01/depat/del/?nid={{ queryson.id }}">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
</div>
    </div>
{% endblock %}

app01/templates/login.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>登录界面</title>

<style>
html,body{
	margin:0px;
	width:100%;
	height:100%;
	overflow:hidden;
	background:#000;
}

#canvas{
	width:100%;
	height:100%;
}
</style>
</head>
<body>
<div style="text-align: end;margin: 16px"><a href="/app01/admin/register/" style="color: #efd5d5">注册新用户？</a></div>
<canvas id="canvas"></canvas>
<div class="account" style="color: #fff;position: absolute;top: 50%;right: 50%;">
        <form method="post">
            {% csrf_token %}
            <div>用户名:</div>
            {{ form.name }}
            <div>密码:</div>
            {{ form.password }}
            {{ form.password.errors.0 }}
            <div class="form-group">
                <label for="id_code">验证码:</label>
                <div class="col-xs-7">
                   {{ form.code }}
                   {{ form.code.errors.0 }}
                </div>
                   <div class="col-xs-5">
                    <img id="image_code" src="/app01/images/code/">
                </div>
            </div>
            <button type="submit" class="btn btn-default">登录</button>
        </form>
    </div>
<div id="" style="color: #fff;position: absolute;top: 50%;right: 50%;">
</div>
<script>
function initVars(){

	pi=Math.PI;
	ctx=canvas.getContext("2d");
	canvas.width=canvas.clientWidth;
	canvas.height=canvas.clientHeight;
	cx=canvas.width/2;
	cy=canvas.height/2;
	playerZ=-25;
	playerX=playerY=playerVX=playerVY=playerVZ=pitch=yaw=pitchV=yawV=0;
	scale=600;
	seedTimer=0;seedInterval=5,seedLife=100;gravity=.02;
	seeds=new Array();
	sparkPics=new Array();
	s="https://cantelope.org/NYE/";
	for(i=1;i<=10;++i){
		sparkPic=new Image();
		sparkPic.src=s+"spark"+i+".png";
		sparkPics.push(sparkPic);
	}
	sparks=new Array();
	pow1=new Audio(s+"pow1.ogg");
	pow2=new Audio(s+"pow2.ogg");
	pow3=new Audio(s+"pow3.ogg");
	pow4=new Audio(s+"pow4.ogg");
	frames = 0;
}

function rasterizePoint(x,y,z){

	var p,d;
	x-=playerX;
	y-=playerY;
	z-=playerZ;
	p=Math.atan2(x,z);
	d=Math.sqrt(x*x+z*z);
	x=Math.sin(p-yaw)*d;
	z=Math.cos(p-yaw)*d;
	p=Math.atan2(y,z);
	d=Math.sqrt(y*y+z*z);
	y=Math.sin(p-pitch)*d;
	z=Math.cos(p-pitch)*d;
	var rx1=-1000,ry1=1,rx2=1000,ry2=1,rx3=0,ry3=0,rx4=x,ry4=z,uc=(ry4-ry3)*(rx2-rx1)-(rx4-rx3)*(ry2-ry1);
	if(!uc) return {x:0,y:0,d:-1};
	var ua=((rx4-rx3)*(ry1-ry3)-(ry4-ry3)*(rx1-rx3))/uc;
	var ub=((rx2-rx1)*(ry1-ry3)-(ry2-ry1)*(rx1-rx3))/uc;
	if(!z)z=.000000001;
	if(ua>0&&ua<1&&ub>0&&ub<1){
		return {
			x:cx+(rx1+ua*(rx2-rx1))*scale,
			y:cy+y/z*scale,
			d:Math.sqrt(x*x+y*y+z*z)
		};
	}else{
		return {
			x:cx+(rx1+ua*(rx2-rx1))*scale,
			y:cy+y/z*scale,
			d:-1
		};
	}
}

function spawnSeed(){

	seed=new Object();
	seed.x=-50+Math.random()*100;
	seed.y=25;
	seed.z=-50+Math.random()*100;
	seed.vx=.1-Math.random()*.2;
	seed.vy=-1.5;//*(1+Math.random()/2);
	seed.vz=.1-Math.random()*.2;
	seed.born=frames;
	seeds.push(seed);
}

function splode(x,y,z){

	t=5+parseInt(Math.random()*150);
	sparkV=1+Math.random()*2.5;
	type=parseInt(Math.random()*3);
	switch(type){
		case 0:
			pic1=parseInt(Math.random()*10);
			break;
		case 1:
			pic1=parseInt(Math.random()*10);
			do{ pic2=parseInt(Math.random()*10); }while(pic2==pic1);
			break;
		case 2:
			pic1=parseInt(Math.random()*10);
			do{ pic2=parseInt(Math.random()*10); }while(pic2==pic1);
			do{ pic3=parseInt(Math.random()*10); }while(pic3==pic1 || pic3==pic2);
			break;
	}
	for(m=1;m<t;++m){
		spark=new Object();
		spark.x=x; spark.y=y; spark.z=z;
		p1=pi*2*Math.random();
		p2=pi*Math.random();
		v=sparkV*(1+Math.random()/6)
		spark.vx=Math.sin(p1)*Math.sin(p2)*v;
		spark.vz=Math.cos(p1)*Math.sin(p2)*v;
		spark.vy=Math.cos(p2)*v;
		switch(type){
			case 0: spark.img=sparkPics[pic1]; break;
			case 1:
				spark.img=sparkPics[parseInt(Math.random()*2)?pic1:pic2];
				break;
			case 2:
				switch(parseInt(Math.random()*3)){
					case 0: spark.img=sparkPics[pic1]; break;
					case 1: spark.img=sparkPics[pic2]; break;
					case 2: spark.img=sparkPics[pic3]; break;
				}
				break;
		}
		spark.radius=25+Math.random()*50;
		spark.alpha=1;
		spark.trail=new Array();
		sparks.push(spark);
	}
	switch(parseInt(Math.random()*4)){
		case 0:	pow=new Audio(s+"pow1.ogg"); break;
		case 1:	pow=new Audio(s+"pow2.ogg"); break;
		case 2:	pow=new Audio(s+"pow3.ogg"); break;
		case 3:	pow=new Audio(s+"pow4.ogg"); break;
	}
	d=Math.sqrt((x-playerX)*(x-playerX)+(y-playerY)*(y-playerY)+(z-playerZ)*(z-playerZ));
	pow.volume=1.5/(1+d/10);
	pow.play();
}

function doLogic(){

	if(seedTimer<frames){
		seedTimer=frames+seedInterval*Math.random()*10;
		spawnSeed();
	}
	for(i=0;i<seeds.length;++i){
		seeds[i].vy+=gravity;
		seeds[i].x+=seeds[i].vx;
		seeds[i].y+=seeds[i].vy;
		seeds[i].z+=seeds[i].vz;
		if(frames-seeds[i].born>seedLife){
			splode(seeds[i].x,seeds[i].y,seeds[i].z);
			seeds.splice(i,1);
		}
	}
	for(i=0;i<sparks.length;++i){
		if(sparks[i].alpha>0 && sparks[i].radius>5){
			sparks[i].alpha-=.01;
			sparks[i].radius/=1.02;
			sparks[i].vy+=gravity;
			point=new Object();
			point.x=sparks[i].x;
			point.y=sparks[i].y;
			point.z=sparks[i].z;
			if(sparks[i].trail.length){
				x=sparks[i].trail[sparks[i].trail.length-1].x;
				y=sparks[i].trail[sparks[i].trail.length-1].y;
				z=sparks[i].trail[sparks[i].trail.length-1].z;
				d=((point.x-x)*(point.x-x)+(point.y-y)*(point.y-y)+(point.z-z)*(point.z-z));
				if(d>9){
					sparks[i].trail.push(point);
				}
			}else{
				sparks[i].trail.push(point);
			}
			if(sparks[i].trail.length>5)sparks[i].trail.splice(0,1);
			sparks[i].x+=sparks[i].vx;
			sparks[i].y+=sparks[i].vy;
			sparks[i].z+=sparks[i].vz;
			sparks[i].vx/=1.075;
			sparks[i].vy/=1.075;
			sparks[i].vz/=1.075;
		}else{
			sparks.splice(i,1);
		}
	}
	p=Math.atan2(playerX,playerZ);
	d=Math.sqrt(playerX*playerX+playerZ*playerZ);
	d+=Math.sin(frames/80)/1.25;
	t=Math.sin(frames/200)/40;
	playerX=Math.sin(p+t)*d;
	playerZ=Math.cos(p+t)*d;
	yaw=pi+p+t;
}

function rgb(col){

	var r = parseInt((.5+Math.sin(col)*.5)*16);
	var g = parseInt((.5+Math.cos(col)*.5)*16);
	var b = parseInt((.5-Math.sin(col)*.5)*16);
	return "#"+r.toString(16)+g.toString(16)+b.toString(16);
}

function draw(){

	ctx.clearRect(0,0,cx*2,cy*2);

	ctx.fillStyle="#ff8";
	for(i=-100;i<100;i+=3){
		for(j=-100;j<100;j+=4){
			x=i;z=j;y=25;
			point=rasterizePoint(x,y,z);
			if(point.d!=-1){
				size=250/(1+point.d);
				d = Math.sqrt(x * x + z * z);
				a = 0.75 - Math.pow(d / 100, 6) * 0.75;
				if(a>0){
					ctx.globalAlpha = a;
					ctx.fillRect(point.x-size/2,point.y-size/2,size,size);
				}
			}
		}
	}
	ctx.globalAlpha=1;
	for(i=0;i<seeds.length;++i){
		point=rasterizePoint(seeds[i].x,seeds[i].y,seeds[i].z);
		if(point.d!=-1){
			size=200/(1+point.d);
			ctx.fillRect(point.x-size/2,point.y-size/2,size,size);
		}
	}
	point1=new Object();
	for(i=0;i<sparks.length;++i){
		point=rasterizePoint(sparks[i].x,sparks[i].y,sparks[i].z);
		if(point.d!=-1){
			size=sparks[i].radius*200/(1+point.d);
			if(sparks[i].alpha<0)sparks[i].alpha=0;
			if(sparks[i].trail.length){
				point1.x=point.x;
				point1.y=point.y;
				switch(sparks[i].img){
					case sparkPics[0]:ctx.strokeStyle="#f84";break;
					case sparkPics[1]:ctx.strokeStyle="#84f";break;
					case sparkPics[2]:ctx.strokeStyle="#8ff";break;
					case sparkPics[3]:ctx.strokeStyle="#fff";break;
					case sparkPics[4]:ctx.strokeStyle="#4f8";break;
					case sparkPics[5]:ctx.strokeStyle="#f44";break;
					case sparkPics[6]:ctx.strokeStyle="#f84";break;
					case sparkPics[7]:ctx.strokeStyle="#84f";break;
					case sparkPics[8]:ctx.strokeStyle="#fff";break;
					case sparkPics[9]:ctx.strokeStyle="#44f";break;
				}
				for(j=sparks[i].trail.length-1;j>=0;--j){
					point2=rasterizePoint(sparks[i].trail[j].x,sparks[i].trail[j].y,sparks[i].trail[j].z);
					if(point2.d!=-1){
						ctx.globalAlpha=j/sparks[i].trail.length*sparks[i].alpha/2;
						ctx.beginPath();
						ctx.moveTo(point1.x,point1.y);
						ctx.lineWidth=1+sparks[i].radius*10/(sparks[i].trail.length-j)/(1+point2.d);
						ctx.lineTo(point2.x,point2.y);
						ctx.stroke();
						point1.x=point2.x;
						point1.y=point2.y;
					}
				}
			}
			ctx.globalAlpha=sparks[i].alpha;
			ctx.drawImage(sparks[i].img,point.x-size/2,point.y-size/2,size,size);
		}
	}
}

function frame(){

	if(frames>100000){
		seedTimer=0;
		frames=0;
	}
	frames++;
	draw();
	doLogic();
	requestAnimationFrame(frame);
}

window.addEventListener("resize",()=>{
	canvas.width=canvas.clientWidth;
	canvas.height=canvas.clientHeight;
	cx=canvas.width/2;
	cy=canvas.height/2;
});

initVars();
frame();
</script>
</body>
</html>

app01/templates/test.html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/tinymce-all-in-one@4.9.3/tinymce.min.js"></script>
  <script>
  tinymce.init({

    selector: '#mytextarea',
    language:'zh_CN',
    plugins: 'image',
    toolbar: 'image',
images_upload_handler: function (blobInfo, succFun, failFun) {
        var xhr, formData;
        var file = blobInfo.blob();//转化为易于理解的file对象
        xhr = new XMLHttpRequest();
        xhr.withCredentials = false;
        xhr.open('POST', '/app01/update/');
        xhr.onload = function() {
            var json;
            if (xhr.status != 200) {
                failFun('HTTP Error: ' + xhr.status);
                return;
            }
            json = JSON.parse(xhr.responseText);
            if (!json || typeof json.location != 'string') {
                failFun('Invalid JSON: ' + xhr.responseText);
                return;
            }
            succFun(json.location);
        };
        formData = new FormData();
        formData.append('file', file, file.name );//此处与源文档不一样
        xhr.send(formData);
    }
});
  </script>
</head>

<body>
<h1>TinyMCE快速开始示例</h1>
  <form method="post">
      {% csrf_token %}
    <textarea id="mytextarea" name="nb">Hello, World!</textarea>
      <button type="submit" class="btn btn-default">提交</button>
  </form>
</body>
</html>

app01/templates/update_pi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="username">
    <input type="file" name="avatar">
    <input type="submit" value="数据提交">
</form>
</body>
</html>

app01/templates/user_add.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            {% for item in form %}
                <div class="form-group">
                    <label>{{ item.label }}:</label>
                        {{ item }}
                        {{ item.errors.0 }}
                </div>
            {% endfor %}

<button type="submit" class="btn btn-default">添加</button>


</form>
    </div>

</div>
{% endblock %}

app01/templates/user_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            {% for item in form %}
                <div class="form-group">
                    <label>{{ item.label }}:</label>
                        {{ item }}
                        {{ item.errors.0 }}
                </div>
            {% endfor %}

<button type="submit" class="btn btn-default">修改</button>


</form>
    </div>

</div>
{% endblock %}

app01/templates/user_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class="container">
    <div><a class="btn btn-success" href="/app01/user/add/"> 新建用户</a></div>
    <div class="panel panel-default">
      <div class="panel-heading">用户信息展示</div>

      <table class="table">
        <thead>
          <tr>

            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>余额</th>
            <th>入职时间</th>
            <th>性别</th>
            <th>所属部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>

          <tr>
               {% for i in queryset %}
            <td>{{ i.id }} </td>
            <td>{{ i.name }}</td>
            <td>{{ i.password }}</td>
            <td>{{ i.age }}</td>
            <td>{{ i.account }}</td>
            <td>{{ i.create_time | date:"Y-m-d" }}</td>
            <td>{{ i.get_gender_display }}</td>
            <td>{{ i.depart.title }}</td>
            <td>
                <a class="btn btn-primary" href="/app01/user/edit/{{ i.id  }}">编辑</a>
                <a class="btn btn-danger" href="/app01/user/del/{{ i.id }}">删除</a>
            </td>
          </tr>
                {% endfor %}

        </tbody>
      </table>
    </div>
</div>
    </div>
{% endblock %}